site_name: "My MkDoxy documentation"

theme:
  name: material

plugins:
  - search
  - mkdoxy:
      projects:
        sharif: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: src # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.hpp*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
